#!/bin/bash

declare -a logs=()
logs+=('jenkins/c3c73f107ecbd4a974ae3022a92d0381/consoleText') # 256
logs+=('jenkins/571c90818e95e56501ec0790dd9ad591/consoleText') # 264
logs+=('jenkins/93f3fbaedcc5425d11a42f27ae5efcb3/consoleText') # 263
logs+=('jenkins/aa2fbb3c0eaa5dcac1cb38dae84b023e/consoleText') # 262
logs+=('jenkins/9d1cf1a8627df34a45001ce2fddf4932/consoleText') # 261
logs+=('jenkins/f843906d48660cac8d614b006e6c3360/consoleText') # 260
logs+=('jenkins/7ec8f4f3774929b112f73c1e59bf48f5/consoleText') # 259
logs+=('log.1') # 258
 
# Digest: sha256:52cb00fba4846d28155a92df3848a6e5fb6268383c6007da9f431eec0087c74d
# Status: Downloaded newer image for voltha/voltha-ci-tools:2.4.0-golangci-lint
# level=info msg="[config_reader] Config search paths: [./ /app /]"
# level=info msg="[config_reader] Used config file .golangci.yml"
# level=info msg="[lintersdb] Active 13 linters: [errcheck goconst gocyclo gofmt goimports gosec gosimple govet ineffassign misspell staticcheck unused whitespace]"
# level=info msg="[lintersdb] Active 13 linters: [errcheck goconst gocyclo gofmt goimports gosec gosimple govet ineffassign misspell staticcheck unused whitespace]"
# level=info msg="[loader] Go packages loading at mode 575 (files|imports|compiled_files|deps|exports_file|name|types_sizes) took 3m57.229880516s"
# level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 147.703725ms"
# level=info msg="[runner/goanalysis_metalinter/goanalysis] analyzers took 4m23.288271345s with top 10 stages: buildssa: 1m10.544536832s, goimports: 37.227482004s, gofmt: 21.910770424s, gosec: 20.27851237s, whitespace: 19.174731834s, ineffassign: 13.449203201s, misspell: 12.588779914s, inspect: 4.781534279s, SA4000: 3.743781118s, shadow: 3.687116567s"
# level=info msg="Memory: 2903 samples, avg is 131.0MB, max is 611.1MB"
# level=info msg="Execution took 6m4.972264423s"
# level=info msg="[runner/unused/goanalysis] analyzers took 19.532130691s with top 10 stages: buildssa: 15.854503822s, U1000: 3.677626869s"
# level=info msg="[runner/skip dirs] Skipped 29 issues from dir internal/test/mocks by pattern internal/test/mocks"
# <testsuites></testsuites>level=info msg="[runner] Issues before processing: 37, after processing: 0"
# level=info msg="[runner] Processors filtering stat (out/in): identifier_marker: 8/8, exclude-rules: 2/2, path_prettifier: 37/37, skip_dirs: 8/37, cgo: 37/37, skip_files: 37/37, nolint: 0/2, filename_unadjuster: 37/37, autogenerated_exclude: 8/8, exclude: 2/8"
# level=info msg="[runner] processing took 198.838419ms with stages: nolint: 163.802257ms, exclude: 17.455992ms, skip_dirs: 16.903535ms, identifier_marker: 356.288µs, path_prettifier: 123.395µs, autogenerated_exclude: 72.88µs, skip_files: 49.109µs, cgo: 37.496µs, filename_unadjuster: 18.551µs, max_same_issues: 4.011µs, source_code: 2.544µs, max_from_linter: 2.383µs, uniq_by_line: 2.19µs, diff: 2.157µs, path_shortener: 2.068µs, exclude-rules: 1.829µs, max_per_file_from_linter: 1.734µs"
# level=info msg="[runner] linters took 2m19.246703223s with stages: goanalysis_metalinter: 1m49.687679668s, unused: 29.359906617s"
# level=info msg="File cache stats: 171 entries of total size 1.9MiB"
# level=error msg="Timeout exceeded: try increase it by passing --timeout option"
# Makefile:106: recipe for target 'sca' failed

declare -a gargs=()
gargs+=('--no-filename')
gargs+=('--fixed-strings')
# gargs+=('-e' 'Execution took')
# gargs+=('-e' 'processing took')
gargs+=('-e' 'linters took')

grep "${gargs[@]}" "${logs[@]}"
